### ISSUE TITLE
ArrayIndexOutOfBoundsException on 1.21.1

### ISSUE THREAD

**Issue by RedstoneFuture** [frengor/VisualFixer#5]
Hello, the plugin even worked until MC 1.20.4. Now there is an error with `VisualFixer v2.2.4` on `PaperMC 1.21.1, build 123`:

https://bytebin.lucko.me/Q45uPMKhYk

I've always just left the plugin installed in case players join with 1.13+ or if graphics bugs occur due to world restrictions.
I would therefore be happy if this error could be fixed, if you want to continue supporting the plugin.

**Comment by frengor** [comment]
Hi! From what I know most of these bugs (if not all, I haven't actually tested this) have already been fixed in 1.15, so I don't think it should be an issue to remove VisualFixer from your server(s). That said, if you're using something like ViaBackwards I don't know if stuff can still be bugged.

The error you're getting is caused by the mess made by Paper in 1.20.6 with unversioned CraftBukkit and mojang-mappings, which broke the NMS code of VisualFixer (so it also probably doesn't happen on Spigot).

I don't currently have the time to update VisualFixer, but I accept PRs if someone wants to improve it (I just saw this project's so old it doesn't use maven, I'll set it up if someone wants to make a PR).

**Comment by RedstoneFuture** [comment]
Okay, all right. Maybe the plugin really isn't that necessary anymore. Thanks anyway for the effort back then.

# Current Status

> "That said, if you're using something like ViaBackwards I don't know if stuff can still be bugged."

According to my test, it does.

## Bug Test without VisualFixer (1.13.2 Client)

Faster test with all activated fix functions in ViaVersion:

- Double Flowers Visual Bug: **still wrong**
- Double Plants Place Visual Bug: _Fixed_
- Break Flower Pot Visual Bug: _Fixed_
- Fast Digging Blocks Visual Bug: _not tested_
- Place Flower in Pots Visual Bug: _Fixed_
- Break Pistons Extension Visual Bug: _Fixed_
- Chorus Break Visual Bug: **still wrong**
- Kelp Break Visual Bug: **still wrong**
- Tall Seagrass Break Visual Bug: **still wrong**

![grafik](https://github.com/user-attachments/assets/b10926ec-38f3-4ccd-a16d-090c74dbfedc)

## Bug Test without VisualFixer (1.17.1 Client)

- Double Flowers Visual Bug: _Fixed_
- Double Plants Place Visual Bug: _Fixed_
- Break Flower Pot Visual Bug: _Fixed_
- Fast Digging Blocks Visual Bug: _not tested_
- Place Flower in Pots Visual Bug: _Fixed_
- Break Pistons Extension Visual Bug: _Fixed_
- Chorus Break Visual Bug: **still wrong**
- Kelp Break Visual Bug: **still wrong**
- Tall Seagrass Break Visual Bug: _Fixed_

## Tested with:
- ViaBackwards v. 5.0.4 with [this](https://bytebin.lucko.me/SOphUQW8qe) config
- ViaVersion v. 5.0.4 with [this](https://bytebin.lucko.me/aK1DTjUxaX) config
- PaperMC v. 1.21.1, build 123
- without VisualFixer

**Comment by frengor** [comment]
Thank you for the testing! :heart:

Seeing the issues with ViaBackwards I'll drop a small update to make it working again.

**Comment by RedstoneFuture** [comment]
Works good. Thank you!
